export const ADD_CONTACT          = 'ADD_CONTACT'
export const DELETE_CONTACT       = 'DELETE_CONTACT'
export const EDIT_CONTACT         = 'EDIT_CONTACT'

export const SET_EMPTY_CONTACT    = 'SET_EMPTY_CONTACT'
export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT'
export const UNSELECT_CONTACT     = 'UNSELECT_SELECTED_CONTACT'